# Generated by Django 4.2.6 on 2023-10-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopowner',
            name='phone',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
