# Generated by Django 4.2.6 on 2023-10-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_workshopowner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopowner',
            name='shopname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
