# Generated by Django 4.2.6 on 2023-10-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_workshopowner_shopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopowner',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
