# Generated by Django 4.2.6 on 2023-12-01 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopdetails', '0005_alter_services_price'),
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_manufacturer', models.CharField(choices=[], max_length=100, null=True)),
                ('light_model_name', models.CharField(choices=[], max_length=100, null=True)),
                ('light_fuel_type', models.CharField(choices=[], max_length=100, null=True)),
                ('mini_manufacturer', models.CharField(choices=[], max_length=100, null=True)),
                ('mini_model_name', models.CharField(choices=[], max_length=100, null=True)),
                ('mini_fuel_type', models.CharField(choices=[], max_length=100, null=True)),
                ('heavy_manufacturer', models.CharField(choices=[], max_length=100, null=True)),
                ('heavy_model_name', models.CharField(choices=[], max_length=100, null=True)),
                ('mini_model_year', models.CharField(choices=[], max_length=100, null=True)),
                ('heavy_fuel_type', models.CharField(choices=[], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookinguser', to=settings.AUTH_USER_MODEL)),
                ('usr_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercategory', to='shopdetails.category')),
            ],
        ),
    ]
