# Generated by Django 4.2.6 on 2023-12-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_servicebooking_heavy_model_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='heavy_fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='heavy_manufacturer',
            field=models.CharField(blank=True, choices=[('Manufacturer X', 'Manufacturer X'), ('Manufacturer Y', 'Manufacturer Y')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='heavy_model_name',
            field=models.CharField(blank=True, choices=[('Model A', 'Model A'), ('Model B', 'Model B'), ('Model C', 'Model C'), ('Model D', 'Model D')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='heavy_model_year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='light_fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='light_manufacturer',
            field=models.CharField(blank=True, choices=[('Manufacturer X', 'Manufacturer X'), ('Manufacturer Y', 'Manufacturer Y')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='light_model_name',
            field=models.CharField(blank=True, choices=[('Model A', 'Model A'), ('Model B', 'Model B'), ('Model C', 'Model C'), ('Model D', 'Model D')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='light_model_year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='mini_fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='mini_manufacturer',
            field=models.CharField(blank=True, choices=[('Manufacturer X', 'Manufacturer X'), ('Manufacturer Y', 'Manufacturer Y')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='mini_model_name',
            field=models.CharField(blank=True, choices=[('Model A', 'Model A'), ('Model B', 'Model B'), ('Model C', 'Model C'), ('Model D', 'Model D')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='mini_model_year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021')], max_length=100, null=True),
        ),
    ]
