# Generated by Django 4.2.6 on 2023-12-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_alter_servicebooking_heavy_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='mini_manufacturer',
            field=models.CharField(blank=True, choices=[('Honda', 'Honda'), ('Hero', 'Hero')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='mini_model_name',
            field=models.CharField(blank=True, choices=[('Unicone', 'Unicone'), ('', 'Model B'), ('Model C', 'Model C'), ('Model D', 'Model D')], max_length=100, null=True),
        ),
    ]
