# Generated by Django 4.2.6 on 2023-12-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_alter_servicebooking_mini_manufacturer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicebooking',
        ),
    ]
