# Generated by Django 4.2.6 on 2023-12-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0007_alter_workshopdetails_branch'),
        ('userside', '0007_requestshop_delete_requestlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestshop',
            name='req_category',
        ),
        migrations.RemoveField(
            model_name='requestshop',
            name='req_service',
        ),
        migrations.AddField(
            model_name='requestshop',
            name='req_category',
            field=models.ManyToManyField(blank=True, related_name='reqcategory', to='shopdetails.category'),
        ),
        migrations.AddField(
            model_name='requestshop',
            name='req_service',
            field=models.ManyToManyField(blank=True, related_name='reqservices', to='shopdetails.services'),
        ),
    ]
