# Generated by Django 4.2.6 on 2023-12-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_remove_requestshop_req_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestshop',
            name='req_service',
        ),
        migrations.AddField(
            model_name='requestshop',
            name='req_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
