# Generated by Django 4.2.6 on 2024-01-15 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticed_location', models.CharField()),
                ('content', models.CharField()),
                ('read', models.BooleanField(default=False)),
                ('noticed_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdetails.workshopdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
