# Generated by Django 4.2.6 on 2024-01-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='noticed_shop',
            field=models.CharField(),
        ),
    ]
