# Generated by Django 4.2.6 on 2024-01-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0002_alter_notifications_noticed_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='read',
        ),
        migrations.AddField(
            model_name='notifications',
            name='group_name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
