# Generated by Django 4.2.6 on 2024-01-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0004_testnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testnotification',
            name='location',
        ),
        migrations.RemoveField(
            model_name='testnotification',
            name='shopname',
        ),
    ]
