# Generated by Django 4.2.6 on 2024-01-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0005_remove_testnotification_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestNotification',
        ),
    ]
