# Generated by Django 4.2.6 on 2024-01-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0006_delete_testnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='group_name',
        ),
    ]
