# Generated by Django 4.2.6 on 2023-10-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
