# Generated by Django 4.2.6 on 2023-12-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profile_usr_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
    ]
