# Generated by Django 4.2.6 on 2023-11-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='heavy_motor_vehicle',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lite_motor_vehicle',
        ),
        migrations.RemoveField(
            model_name='category',
            name='mini_motor_vehicle',
        ),
    ]
