# Generated by Django 4.2.6 on 2023-12-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service',
            new_name='service_name',
        ),
    ]
