# Generated by Django 4.2.6 on 2023-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0002_rename_heavy_motor_vehicle_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
