# Generated by Django 4.2.6 on 2023-12-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0002_rename_service_services_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshopdetails',
            old_name='service',
            new_name='services',
        ),
    ]
