# Generated by Django 4.2.6 on 2023-12-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0003_rename_service_workshopdetails_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopdetails',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proof'),
        ),
    ]
