# Generated by Django 4.2.6 on 2023-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0003_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
