# Generated by Django 4.2.6 on 2023-12-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0005_alter_services_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshopdetails',
            old_name='usr_coordinates',
            new_name='shop_coordinates',
        ),
    ]
