# Generated by Django 4.2.6 on 2023-12-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0006_rename_usr_coordinates_workshopdetails_shop_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopdetails',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
