# Generated by Django 4.2.6 on 2023-12-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetails', '0007_alter_workshopdetails_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopdetails',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proof'),
        ),
    ]
